// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.4
// source: specs/specs.proto

package specs

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MachineSpec is stored in Omni in the infra provisioner state.
type MachineSpec struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Uuid             string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Schematic        string                 `protobuf:"bytes,2,opt,name=schematic,proto3" json:"schematic,omitempty"`
	TalosVersion     string                 `protobuf:"bytes,3,opt,name=talos_version,json=talosVersion,proto3" json:"talos_version,omitempty"`
	VolumeId         string                 `protobuf:"bytes,4,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	Node             string                 `protobuf:"bytes,5,opt,name=node,proto3" json:"node,omitempty"`
	VolumeUploadTask string                 `protobuf:"bytes,6,opt,name=volume_upload_task,json=volumeUploadTask,proto3" json:"volume_upload_task,omitempty"`
	VmCreateTask     string                 `protobuf:"bytes,7,opt,name=vm_create_task,json=vmCreateTask,proto3" json:"vm_create_task,omitempty"`
	VmStartTask      string                 `protobuf:"bytes,8,opt,name=vm_start_task,json=vmStartTask,proto3" json:"vm_start_task,omitempty"`
	VmStopTask       string                 `protobuf:"bytes,9,opt,name=vm_stop_task,json=vmStopTask,proto3" json:"vm_stop_task,omitempty"`
	VmDeleteTask     string                 `protobuf:"bytes,10,opt,name=vm_delete_task,json=vmDeleteTask,proto3" json:"vm_delete_task,omitempty"`
	Vmid             int32                  `protobuf:"varint,11,opt,name=vmid,proto3" json:"vmid,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MachineSpec) Reset() {
	*x = MachineSpec{}
	mi := &file_specs_specs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineSpec) ProtoMessage() {}

func (x *MachineSpec) ProtoReflect() protoreflect.Message {
	mi := &file_specs_specs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineSpec.ProtoReflect.Descriptor instead.
func (*MachineSpec) Descriptor() ([]byte, []int) {
	return file_specs_specs_proto_rawDescGZIP(), []int{0}
}

func (x *MachineSpec) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *MachineSpec) GetSchematic() string {
	if x != nil {
		return x.Schematic
	}
	return ""
}

func (x *MachineSpec) GetTalosVersion() string {
	if x != nil {
		return x.TalosVersion
	}
	return ""
}

func (x *MachineSpec) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *MachineSpec) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *MachineSpec) GetVolumeUploadTask() string {
	if x != nil {
		return x.VolumeUploadTask
	}
	return ""
}

func (x *MachineSpec) GetVmCreateTask() string {
	if x != nil {
		return x.VmCreateTask
	}
	return ""
}

func (x *MachineSpec) GetVmStartTask() string {
	if x != nil {
		return x.VmStartTask
	}
	return ""
}

func (x *MachineSpec) GetVmStopTask() string {
	if x != nil {
		return x.VmStopTask
	}
	return ""
}

func (x *MachineSpec) GetVmDeleteTask() string {
	if x != nil {
		return x.VmDeleteTask
	}
	return ""
}

func (x *MachineSpec) GetVmid() int32 {
	if x != nil {
		return x.Vmid
	}
	return 0
}

var File_specs_specs_proto protoreflect.FileDescriptor

const file_specs_specs_proto_rawDesc = "" +
	"\n" +
	"\x11specs/specs.proto\x12\bemuspecs\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xe9\x02\n" +
	"\vMachineSpec\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1c\n" +
	"\tschematic\x18\x02 \x01(\tR\tschematic\x12#\n" +
	"\rtalos_version\x18\x03 \x01(\tR\ftalosVersion\x12\x1b\n" +
	"\tvolume_id\x18\x04 \x01(\tR\bvolumeId\x12\x12\n" +
	"\x04node\x18\x05 \x01(\tR\x04node\x12,\n" +
	"\x12volume_upload_task\x18\x06 \x01(\tR\x10volumeUploadTask\x12$\n" +
	"\x0evm_create_task\x18\a \x01(\tR\fvmCreateTask\x12\"\n" +
	"\rvm_start_task\x18\b \x01(\tR\vvmStartTask\x12 \n" +
	"\fvm_stop_task\x18\t \x01(\tR\n" +
	"vmStopTask\x12$\n" +
	"\x0evm_delete_task\x18\n" +
	" \x01(\tR\fvmDeleteTask\x12\x12\n" +
	"\x04vmid\x18\v \x01(\x05R\x04vmidB=Z;github.com/siderolabs/omni-infra-provider-proxmox/api/specsb\x06proto3"

var (
	file_specs_specs_proto_rawDescOnce sync.Once
	file_specs_specs_proto_rawDescData []byte
)

func file_specs_specs_proto_rawDescGZIP() []byte {
	file_specs_specs_proto_rawDescOnce.Do(func() {
		file_specs_specs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_specs_specs_proto_rawDesc), len(file_specs_specs_proto_rawDesc)))
	})
	return file_specs_specs_proto_rawDescData
}

var file_specs_specs_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_specs_specs_proto_goTypes = []any{
	(*MachineSpec)(nil), // 0: emuspecs.MachineSpec
}
var file_specs_specs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_specs_specs_proto_init() }
func file_specs_specs_proto_init() {
	if File_specs_specs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_specs_specs_proto_rawDesc), len(file_specs_specs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_specs_specs_proto_goTypes,
		DependencyIndexes: file_specs_specs_proto_depIdxs,
		MessageInfos:      file_specs_specs_proto_msgTypes,
	}.Build()
	File_specs_specs_proto = out.File
	file_specs_specs_proto_goTypes = nil
	file_specs_specs_proto_depIdxs = nil
}
